### ISSUE TITLE
Compare "d=" with the Message Sender (From header)?

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [PHPMailer/DKIMValidator#6]
Why is there no verification if the sender's domain is compatible with the DKIM-Signature domain, parameter "d ="?

**Comment by Synchro** [comment]
I think matching of those is a DMARC concern, not DKIM, not 100% on that though. Regardless, everything is changing in this project and I'm going to be abandoning what's in the master branch right now in favour of what's in dev. It retains almost nothing from the original implementation.
