### ISSUE TITLE
When will the new development version be available?

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [PHPMailer/DKIMValidator#8]
In the current version I have the error "error: 0909006C: PEM routines: get_name: no start line" and maybe the new version solves this problem
for this function
https://github.com/PHPMailer/DKIMValidator/blob/1d84f39debb9eae9dabd4f8fba5f36f442a519b3/src/Validator.php#L352

**Comment by Synchro** [comment]
That sounds like your key is not in the right format, so check that. The dev version still has some way to go, no idea when I'll finish it.
